// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbplnNVRpBEZXzgX3wwJx9OoEIQwb63vA',
    appId: '1:1088854800231:web:ed81e300135dd5317de1c2',
    messagingSenderId: '1088854800231',
    projectId: 'class-demo-70c1f',
    authDomain: 'class-demo-70c1f.firebaseapp.com',
    storageBucket: 'class-demo-70c1f.firebasestorage.app',
    measurementId: 'G-D4Z4C63ZFR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxKwJMQEINgXKM02jMGhF3XBlvGn1zkBs',
    appId: '1:1088854800231:android:3b6cba59c713b0457de1c2',
    messagingSenderId: '1088854800231',
    projectId: 'class-demo-70c1f',
    storageBucket: 'class-demo-70c1f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBR4go__L2MmIFUKQW9mvMCjzzhl8izTTE',
    appId: '1:1088854800231:ios:51c104f482cfb0ca7de1c2',
    messagingSenderId: '1088854800231',
    projectId: 'class-demo-70c1f',
    storageBucket: 'class-demo-70c1f.firebasestorage.app',
    iosClientId: '1088854800231-lheis4dk7rsscae7gpf09mdamh57aj0q.apps.googleusercontent.com',
    iosBundleId: 'com.example.riverpodExample',
  );
}
